apiVersion: numaplane.numaproj.io/v1alpha1
kind: NumaflowControllerRollout
metadata:
  name: numaflow-controller # The Only support name is: numaflow-controller, to prevent having more than one controller in a namespace.
  namespace: example-namespace
spec:
  controller:
    version: "master-9-6-24"
